name: example_module
description: An example module meant to be dynamically loaded
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  app:
    path: ../app

# Here we declare an entrypoint "main"
# It will be used to find the ExampleModule class
entrypoints:
  main: 'package:example_module/example_module.dart'

publish_to: none

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
